/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\TJ\\AppData\\Roaming\\npm\\node_modules\\vuepress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-4fe910fd",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4fe910fd").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-351edff0",
    path: "/views/about/resume.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-351edff0").then(next)
    },
  },
  {
    name: "v-5dbfee04",
    path: "/messageRoom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5dbfee04").then(next)
    },
  },
  {
    name: "v-c0aec0f8",
    path: "/views/springcloud/0-SpringCloud-catalog.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c0aec0f8").then(next)
    },
  },
  {
    name: "v-3f27dd28",
    path: "/views/springcloud/1-SpringCloud-----sc-springcloud.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3f27dd28").then(next)
    },
  },
  {
    name: "v-25686d34",
    path: "/views/about/author.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-25686d34").then(next)
    },
  },
  {
    name: "v-463ebdcc",
    path: "/views/springcloud/2-SpringCloud-----sc-eureka-server.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-463ebdcc").then(next)
    },
  },
  {
    name: "v-7d16ad04",
    path: "/views/springcloud/3-SpringCloud-----sc-common.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7d16ad04").then(next)
    },
  },
  {
    name: "v-61581b5c",
    path: "/views/springcloud/4-SpringCloud-----sc-api-gateway.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-61581b5c").then(next)
    },
  },
  {
    name: "v-40400d44",
    path: "/views/springcloud/5-SpringCloud-----sc-provide-server.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-40400d44").then(next)
    },
  },
  {
    name: "v-e8cca950",
    path: "/views/springcloud/6-SpringCloud-----sc-security-auth.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e8cca950").then(next)
    },
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-0bfa9891",
    path: "/tag/springcloud/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-0bfa9891").then(next)
    },
    meta: {"pid":"tags","id":"springcloud"}
  },
  {
    path: "/tag/springcloud/index.html",
    redirect: "/tag/springcloud/"
  },
  {
    name: "v-ca47dc28",
    path: "/tag/eureka/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-ca47dc28").then(next)
    },
    meta: {"pid":"tags","id":"eureka"}
  },
  {
    path: "/tag/eureka/index.html",
    redirect: "/tag/eureka/"
  },
  {
    name: "v-268fc5ba",
    path: "/tag/common/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-268fc5ba").then(next)
    },
    meta: {"pid":"tags","id":"common"}
  },
  {
    path: "/tag/common/index.html",
    redirect: "/tag/common/"
  },
  {
    name: "v-ffc7ad50",
    path: "/categories/微服务-springcloud/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-ffc7ad50").then(next)
    },
    meta: {"pid":"categories","id":"微服务-springcloud"}
  },
  {
    path: "/categories/微服务-springcloud/index.html",
    redirect: "/categories/微服务-springcloud/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]