/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Nooblack",
  "description": "一个被程序员耽误了的...",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "name": "baidu_union_verify",
        "content": "a0036ccf0b657813fb236f80f376c429"
      }
    ],
    [
      "link",
      {
        "rel": "icon",
        "href": "/images/favicon.svg"
      }
    ],
    [
      "meta",
      {
        "name": "Keywords",
        "content": "T先生,T先生的主页,nooblack,NooBlack,nooblack.cc,NooBlack.cc"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "T先生,T先生的主页,nooblack,NooBlack,nooblack.cc,NooBlack.cc"
      }
    ],
    [
      "script",
      {},
      "var _hmt = _hmt || [];\n    (function() {\n      var hm = document.createElement(\"script\");\n      hm.src = \"https://hm.baidu.com/hm.js?668842dc21c1b8f215b000531ec8f69e\";\n      var s = document.getElementsByTagName(\"script\")[0]; \n      s.parentNode.insertBefore(hm, s);\n    })();"
    ],
    [
      "script",
      {
        "src": "/utils/js/jq3.5.1.js"
      },
      ""
    ],
    [
      "script",
      {
        "src": "/utils/js/click.js"
      },
      ""
    ],
    [
      "script",
      {
        "src": "/js/1.js"
      },
      ""
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "tagline": "IF（BOOL 学习= =FALSE）BOOL 落后=TRUE；不断的学习，我们才能不断的前进",
        "heroText": "Nooblack",
        "bgImageStyle": {
          "height": "100vh"
        },
        "heroTextStyle": {
          "color": "#fff"
        },
        "isShowTitleInHome": false,
        "readingShow": "top"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-4fe910fd",
      "path": "/"
    },
    {
      "title": "简历",
      "frontmatter": {
        "title": "简历",
        "date": "2020-11-11T13:56:00.000Z",
        "sidebar": "auto",
        "keys": [
          "e10adc3949ba59abbe56e057f20f883e"
        ],
        "publish": false,
        "readingShow": "top"
      },
      "regularPath": "/views/about/resume.html",
      "relativePath": "views/about/resume.md",
      "key": "v-351edff0",
      "path": "/views/about/resume.html",
      "headers": [
        {
          "level": 2,
          "title": "这是我的个人简历",
          "slug": "这是我的个人简历"
        }
      ]
    },
    {
      "title": "留言板",
      "frontmatter": {
        "title": "留言板",
        "date": "2020-10-15T00:00:00.000Z",
        "sidebar": false,
        "subSidebar": false,
        "isShowComments": true,
        "readingShow": "top"
      },
      "regularPath": "/messageRoom.html",
      "relativePath": "messageRoom.md",
      "key": "v-5dbfee04",
      "path": "/messageRoom.html",
      "headers": [
        {
          "level": 2,
          "title": "欢迎大家在此留下你的建议和意见",
          "slug": "欢迎大家在此留下你的建议和意见"
        }
      ]
    },
    {
      "title": "SpringCloud的目录结构",
      "frontmatter": {
        "title": "SpringCloud的目录结构",
        "date": "2021-06-30T12:51:00.000Z",
        "sidebar": "auto",
        "categories": [
          "微服务-springcloud"
        ],
        "tags": [
          "springcloud"
        ],
        "sticky": 1,
        "readingShow": "top"
      },
      "regularPath": "/views/springcloud/0-SpringCloud-catalog.html",
      "relativePath": "views/springcloud/0-SpringCloud-catalog.md",
      "key": "v-c0aec0f8",
      "path": "/views/springcloud/0-SpringCloud-catalog.html",
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>如何搭建一个属于自己的微服务框架？请看这里</p>\n</div>"
    },
    {
      "title": "SpringCloud-----sc-springcloud",
      "frontmatter": {
        "title": "SpringCloud-----sc-springcloud",
        "date": "2021-07-01T16:51:00.000Z",
        "sidebar": "auto",
        "categories": [
          "微服务-springcloud"
        ],
        "tags": [
          "springcloud"
        ],
        "readingShow": "top"
      },
      "regularPath": "/views/springcloud/1-SpringCloud-----sc-springcloud.html",
      "relativePath": "views/springcloud/1-SpringCloud-----sc-springcloud.md",
      "key": "v-3f27dd28",
      "path": "/views/springcloud/1-SpringCloud-----sc-springcloud.html",
      "headers": [
        {
          "level": 3,
          "title": "一、IDEA创建一个Maven项目",
          "slug": "一、idea创建一个maven项目"
        },
        {
          "level": 3,
          "title": "二、删除src文件，pom.xml设置如下",
          "slug": "二、删除src文件-pom-xml设置如下"
        },
        {
          "level": 3,
          "title": "三、父目录搭建完毕",
          "slug": "三、父目录搭建完毕"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>一、构建微服务第一步，搭建父级目录</p>\n</div>"
    },
    {
      "title": "关于作者",
      "frontmatter": {
        "title": "关于作者",
        "date": "2021-03-15T14:20:00.000Z",
        "sidebar": "auto",
        "readingShow": "top"
      },
      "regularPath": "/views/about/author.html",
      "relativePath": "views/about/author.md",
      "key": "v-25686d34",
      "path": "/views/about/author.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        }
      ],
      "excerpt": ""
    },
    {
      "title": "SpringCloud-----sc-eureka-server",
      "frontmatter": {
        "title": "SpringCloud-----sc-eureka-server",
        "date": "2021-07-02T16:51:00.000Z",
        "sidebar": "auto",
        "categories": [
          "微服务-springcloud"
        ],
        "tags": [
          "springcloud",
          "eureka"
        ],
        "readingShow": "top"
      },
      "regularPath": "/views/springcloud/2-SpringCloud-----sc-eureka-server.html",
      "relativePath": "views/springcloud/2-SpringCloud-----sc-eureka-server.md",
      "key": "v-463ebdcc",
      "path": "/views/springcloud/2-SpringCloud-----sc-eureka-server.html",
      "headers": [
        {
          "level": 3,
          "title": "一、父级目录下构建Springboot项目---->New->Module->Spring Initializr",
          "slug": "一、父级目录下构建springboot项目-new-module-spring-initializr"
        },
        {
          "level": 3,
          "title": "二、pom.xml文件更改，删除无用设置，将父级引用设置为sc-springcloud",
          "slug": "二、pom-xml文件更改-删除无用设置-将父级引用设置为sc-springcloud"
        },
        {
          "level": 3,
          "title": "",
          "slug": "-2"
        },
        {
          "level": 3,
          "title": "三、添加完子模块sc-eureka-server后，进行对父模块sc-springcloud的pom.xml文件设置",
          "slug": "三、添加完子模块sc-eureka-server后-进行对父模块sc-springcloud的pom-xml文件设置"
        },
        {
          "level": 3,
          "title": "四、进行sc-eureka-server配置",
          "slug": "四、进行sc-eureka-server配置"
        },
        {
          "level": 3,
          "title": "六、配置完成后，启动服务",
          "slug": "六、配置完成后-启动服务"
        },
        {
          "level": 3,
          "title": "五、访问eureka服务，并输入账户密码admin，admin",
          "slug": "五、访问eureka服务-并输入账户密码admin-admin"
        },
        {
          "level": 3,
          "title": "六、大功告成",
          "slug": "六、大功告成"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>二、构建微服务第二步，搭建注册服务</p>\n</div>"
    },
    {
      "title": "SpringCloud-----sc-common",
      "frontmatter": {
        "title": "SpringCloud-----sc-common",
        "date": "2021-07-03T16:51:00.000Z",
        "sidebar": "auto",
        "categories": [
          "微服务-springcloud"
        ],
        "tags": [
          "springcloud",
          "common"
        ],
        "readingShow": "top"
      },
      "regularPath": "/views/springcloud/3-SpringCloud-----sc-common.html",
      "relativePath": "views/springcloud/3-SpringCloud-----sc-common.md",
      "key": "v-7d16ad04",
      "path": "/views/springcloud/3-SpringCloud-----sc-common.html",
      "headers": [
        {
          "level": 3,
          "title": "一、父级目录下构建maven项目---->New->Module->Maven",
          "slug": "一、父级目录下构建maven项目-new-module-maven"
        },
        {
          "level": 3,
          "title": "二、pom.xml事先配置一些公共jar包",
          "slug": "二、pom-xml事先配置一些公共jar包"
        },
        {
          "level": 3,
          "title": "三、公用实体类和工具类",
          "slug": "三、公用实体类和工具类"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>三、构建微服务第三步，搭建公共服务</p>\n</div>"
    },
    {
      "title": "SpringCloud-----sc-api-gateway",
      "frontmatter": {
        "title": "SpringCloud-----sc-api-gateway",
        "date": "2021-07-04T16:51:00.000Z",
        "sidebar": "auto",
        "categories": [
          "微服务-springcloud"
        ],
        "tags": [
          "springcloud"
        ],
        "readingShow": "top"
      },
      "regularPath": "/views/springcloud/4-SpringCloud-----sc-api-gateway.html",
      "relativePath": "views/springcloud/4-SpringCloud-----sc-api-gateway.md",
      "key": "v-61581b5c",
      "path": "/views/springcloud/4-SpringCloud-----sc-api-gateway.html",
      "headers": [
        {
          "level": 3,
          "title": "一、父级目录下构建Springboot项目---->New->Module->Spring Initializr",
          "slug": "一、父级目录下构建springboot项目-new-module-spring-initializr"
        },
        {
          "level": 3,
          "title": "二、pom.xml文件更改，删除无用设置，将父级引用设置为sc-springcloud",
          "slug": "二、pom-xml文件更改-删除无用设置-将父级引用设置为sc-springcloud"
        },
        {
          "level": 3,
          "title": "",
          "slug": "-2"
        },
        {
          "level": 3,
          "title": "三、添加完子模块sc-eureka-server后，进行对父模块sc-springcloud的pom.xml文件设置",
          "slug": "三、添加完子模块sc-eureka-server后-进行对父模块sc-springcloud的pom-xml文件设置"
        },
        {
          "level": 3,
          "title": "五、进行sc-api-gateway配置",
          "slug": "五、进行sc-api-gateway配置"
        },
        {
          "level": 3,
          "title": "六、配置完成后，启动服务",
          "slug": "六、配置完成后-启动服务"
        },
        {
          "level": 3,
          "title": "七、访问eureka服务，并输入账户密码admin，admin",
          "slug": "七、访问eureka服务-并输入账户密码admin-admin"
        },
        {
          "level": 3,
          "title": "八、看到sc-api-gateway注册成功便大功告成",
          "slug": "八、看到sc-api-gateway注册成功便大功告成"
        },
        {
          "level": 3,
          "title": "九、简述",
          "slug": "九、简述"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>四、构建微服务第四步，搭建网关服务</p>\n</div>"
    },
    {
      "title": "SpringCloud-----sc-provide-server",
      "frontmatter": {
        "title": "SpringCloud-----sc-provide-server",
        "date": "2021-07-05T16:51:00.000Z",
        "sidebar": "auto",
        "categories": [
          "微服务-springcloud"
        ],
        "tags": [
          "springcloud"
        ],
        "readingShow": "top"
      },
      "regularPath": "/views/springcloud/5-SpringCloud-----sc-provide-server.html",
      "relativePath": "views/springcloud/5-SpringCloud-----sc-provide-server.md",
      "key": "v-40400d44",
      "path": "/views/springcloud/5-SpringCloud-----sc-provide-server.html",
      "headers": [
        {
          "level": 3,
          "title": "一、父级目录下构建Springboot项目---->New->Module->Spring Initializr",
          "slug": "一、父级目录下构建springboot项目-new-module-spring-initializr"
        },
        {
          "level": 3,
          "title": "二、pom.xml文件更改，删除无用设置，将父级引用设置为sc-springcloud",
          "slug": "二、pom-xml文件更改-删除无用设置-将父级引用设置为sc-springcloud"
        },
        {
          "level": 3,
          "title": "",
          "slug": "-2"
        },
        {
          "level": 3,
          "title": "三、添加完子模块sc-provide-server后，进行对父模块sc-springcloud的pom.xml文件设置",
          "slug": "三、添加完子模块sc-provide-server后-进行对父模块sc-springcloud的pom-xml文件设置"
        },
        {
          "level": 3,
          "title": "四、进行sc-provide-server配置",
          "slug": "四、进行sc-provide-server配置"
        },
        {
          "level": 3,
          "title": "六、配置完成后，启动服务",
          "slug": "六、配置完成后-启动服务"
        },
        {
          "level": 3,
          "title": "五、访问eureka服务，并输入账户密码admin，admin",
          "slug": "五、访问eureka服务-并输入账户密码admin-admin"
        },
        {
          "level": 3,
          "title": "六、大功告成",
          "slug": "六、大功告成"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>五、构建微服务第五步，搭建提供者服务</p>\n</div>"
    },
    {
      "title": "SpringCloud-----sc-security-auth",
      "frontmatter": {
        "title": "SpringCloud-----sc-security-auth",
        "date": "2021-07-06T16:51:00.000Z",
        "sidebar": "auto",
        "categories": [
          "微服务-springcloud"
        ],
        "tags": [
          "springcloud"
        ],
        "readingShow": "top"
      },
      "regularPath": "/views/springcloud/6-SpringCloud-----sc-security-auth.html",
      "relativePath": "views/springcloud/6-SpringCloud-----sc-security-auth.md",
      "key": "v-e8cca950",
      "path": "/views/springcloud/6-SpringCloud-----sc-security-auth.html",
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>六、构建微服务第六步，搭建认证服务</p>\n</div>"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline",
        "readingShow": "top"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "springcloud Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/springcloud/",
      "key": "v-0bfa9891",
      "path": "/tag/springcloud/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "eureka Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/eureka/",
      "key": "v-ca47dc28",
      "path": "/tag/eureka/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "common Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/common/",
      "key": "v-268fc5ba",
      "path": "/tag/common/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "微服务-springcloud Categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/%E5%BE%AE%E6%9C%8D%E5%8A%A1-springcloud/",
      "key": "v-ffc7ad50",
      "path": "/categories/微服务-springcloud/"
    }
  ],
  "themeConfig": {
    "type": "blog",
    "fullscreen": true,
    "logo": "/images/favicon.svg",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "分类"
      },
      "tag": {
        "location": 3,
        "text": "标签"
      }
    },
    "sidebarDepth": 2,
    "subSidebar": "auto",
    "sidebar": "auto",
    "author": "Nooblack",
    "authorAvatar": "/images/avatar.svg",
    "mode": "light",
    "codeTheme": "tomorrow",
    "record": "苏ICP备20016681号",
    "recordLink": "https://icp.chinaz.com/home/info?host=nooblack.com",
    "smooth": "true",
    "valineConfig": {
      "appId": "p9RMajPY54IuBDIxOEPMca8n-gzGzoHsz",
      "appKey": "PLNNKe479eXutkmCJEg2Xv1E",
      "recordIP": true,
      "placeholder": "填写邮箱地址可以及时收到回复噢...",
      "visitor": true
    },
    "lastUpdated": "最后更新于",
    "friendLink": [
      {
        "title": "午后南杂",
        "desc": "Enjoy when you can, and endure when you must.",
        "email": "recoluan@qq.com",
        "link": "https://www.recoluan.com"
      },
      {
        "title": "唐子涵的博客",
        "desc": "至于未来会怎么样 反正路还长 天总会亮",
        "link": "https://www.zihanzy.com/"
      },
      {
        "title": "李Sir的博客",
        "desc": "活在当下",
        "link": "https://heroli.netlify.app/"
      }
    ],
    "nav": [
      {
        "text": "主页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "工具箱",
        "icon": "iconfont icon-tools",
        "items": [
          {
            "text": "在线JSON解析",
            "link": "https://www.sojson.com/"
          },
          {
            "text": "在线JSON生成实体类",
            "link": "https://www.bejson.com/json2javapojo/new/"
          },
          {
            "text": "编程语言排行榜",
            "link": "https://www.tiobe.com/tiobe-index/"
          }
        ]
      },
      {
        "text": "我的作品",
        "icon": "iconfont icon-tools",
        "items": [
          {
            "text": "CloudMusic\t|\t米奇妙妙屋",
            "link": "https://penggang-home.gitee.io/cloud-music/#/discovery",
            "icon": "iconfont icon-wangyiyunyinle"
          },
          {
            "text": "电商后台管理系统 V：1.3.0",
            "link": "http://120.53.120.229:1921/#/login",
            "icon": "iconfont icon-vue"
          },
          {
            "text": "电商后台管理系统 V：1.2.0",
            "link": "http://120.53.120.229:1920/#/login",
            "icon": "iconfont icon-vue"
          },
          {
            "text": "电商平台实时监控系统(Echarts)",
            "link": "http://120.53.120.229:9989/#/home",
            "icon": "iconfont icon-vue"
          },
          {
            "text": "仿微信聊天",
            "link": "http://120.53.120.229:8100",
            "icon": "reco-wechat"
          }
        ]
      },
      {
        "text": "时间线",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "留言板",
        "icon": "reco-suggestion",
        "link": "/messageRoom"
      },
      {
        "text": "关于",
        "icon": "reco-message",
        "items": [
          {
            "text": "关于我",
            "link": "/views/About/author",
            "icon": "reco-account"
          },
          {
            "text": "简历",
            "link": "/views/About/resume",
            "icon": "reco-document"
          },
          {
            "text": "语雀",
            "link": "https://www.yuque.com/tangtangtangtangtang-clw9m",
            "icon": "reco-csdn"
          },
          {
            "text": "GitHub",
            "link": "https://github.com/penggang-home",
            "icon": "reco-github"
          }
        ]
      }
    ]
  }
}