/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "springcloud": {
      "key": "springcloud",
      "scope": "tags",
      "path": "/tag/springcloud/",
      "pageKeys": [
        "v-c0aec0f8",
        "v-3f27dd28",
        "v-463ebdcc",
        "v-7d16ad04",
        "v-61581b5c",
        "v-40400d44",
        "v-e8cca950"
      ]
    },
    "eureka": {
      "key": "eureka",
      "scope": "tags",
      "path": "/tag/eureka/",
      "pageKeys": [
        "v-463ebdcc"
      ]
    },
    "common": {
      "key": "common",
      "scope": "tags",
      "path": "/tag/common/",
      "pageKeys": [
        "v-7d16ad04"
      ]
    }
  },
  "categories": {
    "微服务-springcloud": {
      "key": "微服务-springcloud",
      "scope": "categories",
      "path": "/categories/微服务-springcloud/",
      "pageKeys": [
        "v-c0aec0f8",
        "v-3f27dd28",
        "v-463ebdcc",
        "v-7d16ad04",
        "v-61581b5c",
        "v-40400d44",
        "v-e8cca950"
      ]
    }
  },
  "timeline": {}
}