/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "springcloud",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/springcloud/","interval":[0,7]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "eureka",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/eureka/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "common",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/common/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "微服务-springcloud",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/微服务-springcloud/","interval":[0,7]}],
  prevText: "Prev",
  nextText: "Next",
}]